[package]
name = "hdpc-dl"
version = "0.1.0"
authors = ["b42-sneak <59374651+b42-sneak@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.7"
scraper = "0.12.0"
select = "0.5.0"
clap = "2.33.2"
